### ISSUE TITLE
Fix or Feature Request(@pure-model/react): prop list of Provider `Model` and `preloadedState` in `ReactModelArgs` has not type constraints

### ISSUE THREAD

**Issue by tqma113** [Lucifier129/pure-model#1]
`Model` and `preloadedState` in `ReactModelArgs`

`preloadedState` should be the `State` type in `Model`， but it is any type now.

Is it my cracking error or is it impossible to do it for some reason?

**Comment by Lucifier129** [comment]
` ReactModelArgs` is now used as `props`, type infer via generic seems not very useful and complex.

`preloadedState` usually passing by the library author, it should add some unit-tests to ensure the correctness.

Have you met a problem?

**Comment by tqma113** [comment]
```ts
// model.ts
import { setupStore } from '@pure-model/core'
import { createReactModel } from '@pure-model/react'

const initialState: number = 0

const update = (state: number, payload: number) => {
  return payload
}

const inscrease = (state: number) => {
  return state + 1
}

const descrease = (state: number) => {
  return state - 1
}

export default createReactModel(() => {
  let { store, actions } = setupStore({
    // 可选参数，会反映到 redux-devtools 里的 name
    name: 'todos',
    // 必选参数：initialState
    initialState,
    // 必须参数：reducers，更新状态函数
    reducers: {
      update,
      inscrease,
      descrease
    },
    // 可选参数，是否开启 redux-logger，默认为 false
    logger: true,
    // 可选参数，是否开启 redux-devtools，默认为 true
    devtools: true,
  })

  // 必须返回 store + actions 的对象结构
  return { store, actions }
})
```

```ts
import React from 'react'
import { Provider } from '@pure-model/react'

import model from './model'

export default () => {
  return (
    <Provider list={[{ Model: model, preloadedState: 'error' }]}>
      ...
    </Provider>
  )
}
```
the `State` type  of `Model` is `number`, when I pass string to `preloadedState` of props of Provider, it do not throw error, expect only allow number pass to `preloadedState` here

**Comment by Lucifier129** [comment]
I had try in some way but failed to infer the right type in `props.list`.

Use `<Model.Provider preloadedState={xxx} />` will work, but need to add each provider manually

**Comment by Lucifier129** [comment]
PR is welcome, we need help:\
