### ISSUE TITLE
Doc Request

### ISSUE THREAD

**Issue by tqma113** [Lucifier129/pure-model#2]
可以加点文档吗？:pray: 很多地方看不懂为什么这么做:sob:
* [core] preload、start、finish 可以理解为 SSR数据初始化、componentDidMount、componentWillUnmount吗？
* [core] context 在这里是为了做什么（放什么内容）？
* [react] 传给 Provider 的 model list 的收集是 import 手动传递，有没有办法不通过 import，通过类似 hook 的函数去添加

**Comment by Lucifier129** [comment]
- preload, start, finish 是 model 层独立抽象的生命周期，它可以跟 view 层的 prerender, didMount, willUnmount 衔接起来，也可以在 unit-test 环境里，主动调用

- model context 是在 model 层实现 react-hooks 类似的依赖注入机制，可以通过 setupContext(ModelContext) 获取到 context，然后封装自己的 custom hooks

- Provider 的 model list 必须手动传递，因为我们需要提前知道 model 去挂载 Model.Provider，不然 Model.useState 访问不到最近的 Context.Provider

如果采用 recoil 那种 build-systems model 设计，可以直挂载一个 RecoilRoot 去统筹所有 RecoilState。不过，单一 Provider 也有劣势，就是不好细分 scope。多 Provider 模式，可以按需在不同组件树层级上，套不同的 XXXModel.Provider 更精细地切分实例， Model.useState 在不同位置可以索引到不同的实例（它们的实例都在最近的 Provider 上）

**Comment by codering** [comment]
@Lucifier129  

- 这个能在小程序上使用吗？

- http接口能否增强？
现在只有get和post，没有put和delete。
如果想统一对请求进行设置，比如在请求前设置header，请求后对数据做转换之类，是不是只能通过setupFetch后再封装一次？这样的话，setuoGetJSON, setuoPostJSON就没啥用了。

**Comment by tqma113** [comment]
@codering 

- 目前应该还没有支持 https://github.com/Lucifier129/pure-model/blob/ed247a3d5cb540b0d152f3f84b2a21dc28d59c99/packages/core/src/env.ts#L4
- 如果你有特殊需求，是需要自己抽象封装了
